#define DEBUG

#define SmartHomeServer_IP "192.168.1.1"
#define SmartHomeServer_PORT 9002
#define LOCAL_UDP_PORT 9000

#define PIN_WALL_SWITCH_PIN D16
#define PIN_CEILING_LIGHTNING_RELAY D17
#define WIFI_RESET_IF_NO_MSG_FROM_SERVER_FOR 120000
#define WIFI_UDP_RESEND_GIVE_UP_AFTER 40
#define WIFI_UDP_RESEND_DELAY_MS 500

